### ISSUE TITLE
Add "magic" properties in lists

### ISSUE THREAD

**Issue by michalwa** [michalwa/mustache-render#3]
Lists of objects should have the following additional properties added automatically for convenience:
 - [ ] `__ord__` - numbering from 1
 - [ ] `__last__` - `True` only for the last element

## Example:
Template:
```mustache
{{#items}}
  {{__index__}}. {{name}}{{^__last__}},
{{/__last__}}
{{/items}}
```
Data:
```yaml
items:
- name: Foo
- name: Bar
- name: Baz
```

Output:
```
1. Foo,
2. Bar,
3. Baz
```
